### ISSUE TITLE
ts4900 hangs at reboot

### ISSUE THREAD

**Issue by mhanuel26** [embeddedarm/linux-3.10.17-imx6#2]
TS-4900 hangs at reboot, the console freezes and last message is 

_failed to disable 1.2GHz OPP_

Confirmed with last 3.14 kernel and TS-8550 board.

![1 2ghz_ts9](https://cloud.githubusercontent.com/assets/2257779/13447697/7fa70044-dfeb-11e5-9334-a3de9de37e26.png)

[REBOOT_ISSUE_TS4900_KERNEL_3.14.zip](https://github.com/embeddedarm/linux-3.10.17-imx6/files/153923/REBOOT_ISSUE_TS4900_KERNEL_3.14.zip)

**Comment by mhanuel26** [comment]
it might be related to this
[http://lists.infradead.org/pipermail/linux-arm-kernel/2014-June/268125.html](url)
Please study this issue since it affects reliability.

**Comment by ts-kris** [comment]
I sincerely apologize for leaving this open for so long. I'm currently working to address all open issues.

Since the creation of this issue, all TS-4900 variants and related platforms have moved to a 4.1 or newer kernel.
