### ISSUE TITLE
Kernel Update

### ISSUE THREAD

**Issue by jhillix** [embeddedarm/linux-3.10.17-imx6#3]
The latest Linux kernel mainline is [5.0-rc7](https://www.kernel.org/) and latest stable is [4.20.11](https://www.kernel.org/). The current kernel version for our board, TS-7970, is 4.1.15. Are there any plans on releasing a newer version?

**Comment by markfeathers** [comment]
Any new kernels will be created as branches on linux-tsimx which has a less confusing name.  We have a 4.9.11 which is supported on the TS-7970 and our other imx6 boards.
https://github.com/embeddedarm/linux-tsimx/tree/ts-imx_4.9.11_1.0.0_ga

4.9 is being supported until 2023 with security patches.  For now you would have to manually patch it, but we are pursuing automatically patching this going forward. 

We will directly support the 4.9.11 kernel, but we are also supported in the upstream kernel:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/boot/dts/imx6qdl-ts7970.dtsi?h=v5.0-rc7

Some features of the board are not supported here.  Last I checked this included WIFI, the ttyMAX uarts, and temp compensation in the RTC.

Is there some specific feature you're looking for in a new kernel?

**Comment by johnp789** [comment]
Control group eBPF hooks, needed for systemd IP accounting, were added in kernel 4.11.  

Systemd CPU accounting can be turned on with less CPU load with kernel 4.15+.

**Comment by ts-kris** [comment]
I'm addressing open issues, I apologize for the silence on the matter.

As Mark said, there is support in the upstream kernel for the TS-7970, however it does lack some of the specific features that are implemented in the NXP kernel tree and other modifications we have made for support.

I can say we have had success with running the upstream 5.10 kernel on the TS-7970

At this time, the 4.9 kernel is LTS and we are planning on keeping the TS-7970 (and family) on this kernel until the LTS support ends, at which time we will work to support these systems on a new LTS kernel.

At this time I'm closing this issue.
